Title: Stickman Boost
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://3kh0.github.io/projects/stickman-boost/index.html
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://3kh0.github.io/projects/stickman-boost/index.html
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
