Title: "Dumb Ways to Die 3: World Tour"
Alternate Titles: Dumb Ways to Die 3
Library: arcade
Series: ""
Developer: " MarketJS"
Publisher: null
Play Mode: Single Player
Release Date: 2019-05-14
Version: null
Languages: en
Extreme: No
Tags: Variety; Simulation
Tag Categories: genre; default
Source: https://gamedistribution.com/games/dumb-ways-to-die-3-world-tour
Platform: HTML5
Status: Playable
Application Path: ":browser-mode:"
Launch Command: http://html5.gamedistribution.com/a91f360648334bc988222f1aff557c4e/index.html
Game Notes: null
Original Description: >-
  
  Play mini games featuring the characters from Dumb Ways to Die. Dumb Ways to Die is a worldwide brand with over 300 million downloads on Apple App Store and Google Play combined. Test your reflexes in this challenging series of mini games, where a milisecond can make the difference between winning and losing. Score coins for each challenge, and use the to repair the once great town of Dumbville.
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
