Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://f3.silvergames.com/marketjs/hardest-game-on-earth/
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://f3.silvergames.com/marketjs/hardest-game-on-earth/
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
