Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://storage.y8.com/y8-studio/unity/joll/death_run_builds/death_run_wasm_v1/index.html?key=y8&ratio_tolerant=true&value=default
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://storage.y8.com/y8-studio/unity/joll/death_run_builds/death_run_wasm_v1/index.html?key=y8&ratio_tolerant=true&value=default
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
