Title: null
Alternate Titles: null
Library: arcade
Series: null
Developer: null
Publisher: null
Play Mode: Single Player
Release Date: null
Version: null
Languages: en
Extreme: No
Tags: ""
Tag Categories: ""
Source: http://www.enjoy4fun.com/game/dukedashingtonremastered/v4/index.html?uid=cc42166rsfeq907ih330&channel-id=3487216655
Platform: HTML5
Status: Playable
Application Path: FPSoftware\Basilisk-Portable\Basilisk-Portable.exe
Launch Command: http://www.enjoy4fun.com/game/dukedashingtonremastered/v4/index.html?uid=cc42166rsfeq907ih330&channel-id=3487216655
Game Notes: null
Original Description: null
Curation Notes: null
Mount Parameters: null
Additional Applications: {}
